### ISSUE TITLE
How do I run it?

### ISSUE THREAD

**Issue by LucaTorre2010** [Still34/AffinityPatcher#2]
Hello, I'm trying to patch affinity designer by running this command:
./AffinityPatcher.exe --input "C:\Program Files\Affinity\Designer 2\Designer.exe"

but I got this error:
Unhandled exception: System.IO.DirectoryNotFoundException: Cannot find the target Affinity directory.
   at AffinityPatcher.Program.<>c.<Main>b__1_0(DirectoryInfo di, Boolean shouldVerbose, Boolean shouldBackup)
   at System.CommandLine.Handler.<>c__DisplayClass4_0`3.<SetHandler>b__0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext)
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

What should I do?
thanks in advance

**Comment by LucaTorre2010** [comment]
Anyways, my system is x64 and I've installed the .exe version, if that helps

**Comment by Still34** [comment]
1. If you are directly modifying the file within Program Files, you need to elevate as admin due to the default strict ACL in all Program Files directories.
2. The expected input is a directory, so in this case it should be `"C:\Program Files\Affinity\Designer 2\"`

**Comment by LucaTorre2010** [comment]
Thank you so much for your help!!! Designer now works without asking me for any product key... You're a lifesaver!

**Comment by possionthefish1** [comment]
Hello, sorry for commenting on the closed issue. Just wanna say thank you for the software. Cheers.

**Comment by Azotej** [comment]
Hello,
I can't understood why I have an issue with patching. As I understood, patcher can't modify all files. I run it in Powershell like administrator, and there what it shows:

 .\AffinityPatcher.exe --input "C:\Program Files\Affinity\Designer 2"
┌─Patched─────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                 │
│ - System.Boolean Serif.Interop.Persona.Application::HasEntitlementToRun()                                       │
│ - System.Boolean Serif.Interop.Persona.Application::CheckEula()                                                 │
│ - System.Boolean Serif.Interop.Persona.Application::get_AllowsOptInAnalytics()                                  │
│ - Serif.Interop.Persona.CrashReportUploadPolicy Serif.Interop.Persona.Application::GetCrashReportUploadPolicy() │
│                                                                                                                 │
│                                                                                                                 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Unhandled exception: System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.FileSystem.MoveFile(String, String, Boolean)
   at System.IO.File.Move(String, String, Boolean)
   at AffinityPatcher.Program.PatchPersonaAssembly(String, Boolean, Boolean)
   at AffinityPatcher.Program.<>c.<Main>b__1_0(DirectoryInfo di, Boolean shouldVerbose, Boolean shouldBackup)
   at System.CommandLine.Handler.<>c__DisplayClass4_0`3.<SetHandler>b__0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext)
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()


Can you, please, help me with solving this?
Thank you

**Comment by Still34** [comment]
Make sure Designer has been closed first. Alternatively, you can copy the DLLs to a different directory that doesn't have strict permission requirements like a folder on your desktop, run the patch there, and copy the DLLs back to the installation directory manually.

**Comment by Azotej** [comment]
So, what I want to say. You are awesome!! Thank you, it helps. As I understood, issue is in Program Files location.

**Comment by Still34** [comment]
no

**Comment by man0avec0plan** [comment]
Can you help me run this correctly?

C:\Users\avina>./AffinityPatcher.exe --input "C:\Program Files\Affinity\Photo 2\Photo.exe"
'.' is not recognized as an internal or external command, operable program or batch file.

The AffinityPatcher exe is in my downloads folder. Does it have to be in the same folder as Photo 2?

**Comment by Still34** [comment]
the ./ is for when you're executing it in PowerShell

**Comment by man0avec0plan** [comment]
> the ./ is for when you're executing it in PowerShell

I had gotten a couple of the steps wrong--works perfectly, thank you!

**Comment by Still34** [comment]
<img width="1440" height="1082" alt="Image" src="https://github.com/user-attachments/assets/3c186370-4d8b-468a-9fa4-461c2c67362e" />

**Comment by Still34** [comment]
Additional instructions have been added to the README, https://github.com/Still34/AffinityPatcher/blob/a1acfeb365d801ac0400ce7ac743b6aa8597420d/README.md?plain=1#L31-L37

**Comment by ibay613** [comment]
Just wanted to thank you again for this! Affinity 3 works perfectly! Are you down for making other patchers for other software?

**Comment by Still34** [comment]
> Just wanted to thank you again for this! Affinity 3 works perfectly! Are you down for making other patchers for other software?

At the moment, no. I will likely only add support for software I'm interested in enough and easy enough to patch via IL.

**Comment by ibay613** [comment]
That's fair. Many thanks again for the patcher. 
Someone released the other AI models in Affinity, if you want to give it a shot in enabling it.

https://gofile.io/d/ALuAVC

**Comment by Beaker003** [comment]
Hi, I am trying to use the patch but I keep messing it up. I am new to this and I kept trying before but I wanted to upload this with a screenshot to see if you could help me. I'm sorry to post on a closed issue, but I've also used the comments here and it hasn't helped me so far. Thank you for your work and I hope you can help me.
<img width="1262" height="292" alt="Image" src="https://github.com/user-attachments/assets/9adb3a94-9cf1-4208-b36e-39a543918694" />
